### ISSUE TITLE
Не стоит использовать теги

### ISSUE THREAD

**Issue by Red-Cat-Fat** [shark2302/Shooter#1]
Особенно таким образом
https://github.com/shark2302/Shooter/blob/0635be0b5db54111ba3bbbb33b4e7e242c287df7/Assets/Scripts/Oblects/Enemy.cs#L189
Если провреять по тегу, то используй `go.CompareTag("tag1")`

**Comment by shark2302** [comment]
Знаю, что плохо это, но вроде бы не настолько https://github.com/shark2302/Shooter/commit/96b998ad268fa2caddf4e3e057cb51aac5636695 поменя на CompareTag

**Comment by Red-Cat-Fat** [comment]
Вообще лучше определять по компоненту. Так как в перспективе для больших игр использование тегов черевато проблемами. Теги больше для пототипирования нужны.
