### ISSUE TITLE
Удаляй неиспользуемые элементы

### ISSUE THREAD

**Issue by Red-Cat-Fat** [shark2302/Shooter#2]
У тебя 2 пустых сцены. Если не используешь - удаляй.
Сюда же допишу слишком высокую чувствительность по вертикали и низкую по горизонтали

**Comment by shark2302** [comment]
https://github.com/shark2302/Shooter/commit/828db201e68112035ce7c7152c0cffcd6b998e59 удалил, я не могу нормально подобрать чувствительность, так как у меня тачпад и мне максимально неудобно)

**Comment by Red-Cat-Fat** [comment]
Понял тебя)
