### ISSUE TITLE
Проверяй канвас на разных разрешениях экрана

### ISSUE THREAD

**Issue by Red-Cat-Fat** [shark2302/Shooter#3]
![image](https://user-images.githubusercontent.com/28541280/81600590-8743bc80-93d2-11ea-92e1-51569b99610d.png)

**Comment by shark2302** [comment]
https://github.com/shark2302/Shooter/commit/60e35ac244449d0a49b98f220e61db5bc9fe30e8 сейчас вроде бы работает на всех разрешениях, могу ошибаться, но у меня точно работает на всех
