### ISSUE TITLE
Проблемы со стейт машиной бота

### ISSUE THREAD

**Issue by Red-Cat-Fat** [shark2302/Shooter#4]
Бот просто затупил. Анимация бега, но стоит, кругом враги - он неактивен

**Comment by shark2302** [comment]
Хорошо, попробую отловить баг

**Comment by Red-Cat-Fat** [comment]
Лучше потрать силы на финальный проект

**Comment by shark2302** [comment]
Да, я собираюсь сдавать данную игру, как итоговый проект, ну еще добавить что-то
