### ISSUE TITLE
Ну нельзя так делать! NRE!!!

### ISSUE THREAD

**Issue by Red-Cat-Fat** [shark2302/Shooter#5]
Прежде чем используешь поля, свойства, функции и методы какого-то компонента необходимо проверить его на null
https://github.com/shark2302/Shooter/blob/65d7a9b17fc81da3f60c6b931938e8edb3719418/Assets/Scripts/BotBehaviours/RushingBehaviour.cs#L13-L14

**Comment by shark2302** [comment]
Это все из-за моей невнимательности. Сейчас прошелся по скриптам, где заметил убрал https://github.com/shark2302/Shooter/commit/9a670cad020ace073ec1dac78c2f0cc42ed2e62c

**Comment by shark2302** [comment]
вот тут лучше https://github.com/shark2302/Shooter/commit/3a0a9da91ca612adeebd80b7f954975219f2fa7c

**Comment by Red-Cat-Fat** [comment]
А `GetBehaviour<IdleBehaviour>()` на null кто проверять будет?)

**Comment by shark2302** [comment]
я буду) https://github.com/shark2302/Shooter/commit/d10e76b5515fb42ccf5437eacc81853f0fef65ad
